# Generated by Django 5.0.6 on 2024-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_descrtiption_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, upload_to='tag_icons/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects_images/'),
        ),
    ]
