# Generated by Django 5.0.6 on 2024-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_show_tag_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects_images/'),
        ),
    ]
