# Generated by Django 5.0.6 on 2024-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectimage_image_url_tag_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
