# Generated by Django 5.0.6 on 2024-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='show',
            new_name='show_projects',
        ),
        migrations.AddField(
            model_name='tag',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
    ]
