# Generated by Django 5.0.6 on 2024-05-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
