# Generated by Django 5.0.6 on 2024-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_page_reverse_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='page_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
