# Generated by Django 5.0.6 on 2024-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact_settings_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
